/**
 * Server-backed storage compatibility layer.
 *
 * The former implementation mirrored Canister/ICP state in a client-side
 * store and synchronised it later. That model is intentionally gone:
 * browser storage, Caffeine, actors, queues, and conflict resolution are not
 * used here. PHP session cookies authenticate requests and MySQL is the only
 * source of truth.
 *
 * New code should use the domain services in `services/` and React Query.
 * These exports remain only for older callers while they are migrated.
 */

import { get, post } from './apiClient';

export type SyncQueueItemType =
  | 'upsertPatient'
  | 'upsertVisit'
  | 'upsertPrescription'
  | 'upsertAppointment'
  | 'upsertQueueEntry'
  | 'upsertObservation'
  | 'upsertBed'
  | 'upsertDailyProgressNote'
  | 'upsertHandover'
  | 'upsertMedicationAdministration'
  | 'upsertFrontPageContent';

export interface SyncQueueItem {
  id: string;
  timestamp: number;
  type?: SyncQueueItemType;
  operation?: 'create' | 'update' | 'delete';
  entityType?: string;
  entityId?: string;
  data: unknown;
  retryCount: number;
}

export interface SyncStatus {
  isOnline: boolean;
  pendingChanges: number;
  lastSyncAt?: Date;
}

export interface SyncConflict {
  entityType: string;
  entityId: string;
  localVersion: unknown;
  serverVersion: unknown;
  localUpdatedAt?: number;
  serverUpdatedAt?: number;
  detectedAt: number;
}

export interface MigrationProgress {
  total: number;
  migrated: number;
  message: string;
}

/** Legacy queue/conflict APIs deliberately do nothing: writes are immediate API writes. */
export function enqueueSync(_item: SyncQueueItem): void {}
export function removeFromQueue(_type: string, _ids: Set<string>): void {}
export function loadSyncQueue(): SyncQueueItem[] { return []; }
export function getConflicts(): SyncConflict[] { return []; }
export function getConflictsCount(): number { return 0; }
export function addConflict(_conflict: SyncConflict): void {}
export function resolveConflict(_entityId: string, _choice: 'mine' | 'theirs'): void {}
export function isMigrationDone(): boolean { return true; }
export function markMigrationDone(): void {}
export function getDeviceId(): string { return 'php-session'; }
export function setLastSyncTs(_ts: number): void {}
export function getPendingChangesCount(): number { return 0; }

/** Read/write the server-side front-page settings stored in MySQL. */
export async function loadFrontPageContentFromServer(): Promise<Record<string, unknown> | null> {
  try {
    return await get<Record<string, unknown>>('/frontpage/get.php');
  } catch {
    return null;
  }
}

export async function saveFrontPageContentToServer(
  data: Record<string, unknown>,
): Promise<boolean> {
  try {
    await post('/frontpage/save.php', data);
    return true;
  } catch {
    return false;
  }
}

/**
 * Compatibility name for old callers. The old actor argument is intentionally
 * absent; authentication is provided by the PHP session cookie.
 */
export async function saveFrontPageContentWithSync(
  data: Record<string, unknown>,
): Promise<void> {
  if (!(await saveFrontPageContentToServer(data))) {
    throw new Error('Unable to save front-page content through the PHP API');
  }
}

const CLINICAL_ENDPOINTS: Record<string, { list: string; create: string }> = {
  encounters: { list: '/clinical/encounters-list.php', create: '/clinical/encounters-create.php' },
  observations: { list: '/clinical/observations-list.php', create: '/clinical/observations-create.php' },
  notes: { list: '/clinical/notes-list.php', create: '/clinical/notes-create.php' },
  orders: { list: '/clinical/orders-list.php', create: '/clinical/orders-create.php' },
  beds: { list: '/beds/list.php', create: '/beds/create.php' },
};

/** Fetch a clinical collection from PHP/MySQL. */
export async function getClinicalEntities(
  entityType: string,
  patientId?: number,
): Promise<unknown[]> {
  const endpoint = CLINICAL_ENDPOINTS[entityType];
  if (!endpoint) throw new Error(`No PHP API endpoint is registered for ${entityType}`);
  const result = await get<unknown[] | { items?: unknown[] }>(endpoint.list,
    patientId === undefined ? undefined : { patientId });
  return Array.isArray(result) ? result : result.items ?? [];
}

/** Create one server-side clinical record; IDs are generated by MySQL. */
export async function createClinicalEntity(
  entityType: string,
  data: Record<string, unknown>,
): Promise<unknown> {
  const endpoint = CLINICAL_ENDPOINTS[entityType];
  if (!endpoint) throw new Error(`No PHP API endpoint is registered for ${entityType}`);
  return post(endpoint.create, data);
}

/**
 * The former whole-store API cannot be implemented safely without reintroducing
 * a client database. Callers must use a domain service or createClinicalEntity.
 */
export function getClinicalStore(): never {
  throw new Error('Clinical data must be read from PHP/MySQL domain APIs');
}
export function saveClinicalEntities(_entityType: string, _items: unknown[]): never {
  throw new Error('Clinical data must be written through PHP/MySQL domain APIs');
}
export function saveClinicalEntitiesWithSync(_entityType: string, _items: unknown[]): never {
  throw new Error('Clinical data must be written through PHP/MySQL domain APIs');
}
export function nextClinicalId(_items: { id?: unknown }[]): never {
  throw new Error('Clinical IDs are generated by MySQL');
}

/** Kept as an async compatibility hook; there is no client-side bootstrap. */
export async function bootstrapFromCanister(): Promise<void> {}
export async function flushContentQueue(): Promise<void> {}
